title: DevNest
description: P치gina para conocer m치s sobre mis proyectos y repositorios.
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "dark"
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-include-cache

# Navegaci칩n principal de ejemplo
nav:
  - title: "Inicio"
    url: "/"
  - title: "Proyectos"
    url: "/proyectos/"

# Configuraci칩n baseurl si usas GitHub Pages en una subcarpeta
baseurl: "/rep-zone"

